%remove 25 bc it is control mouse
% og_context_data = load('W:\Connie\results\Bassi2025\data\context_data.mat').context_data;
context_data_updated.dff = og_context_data.dff(:,[1:24]);
context_data_updated.deconv = og_context_data.deconv(:,[1:24]);
additivity_stats = test_irrelevant_sound_additivity( ...
    context_data_updated, ...
    24, ...
    params.frames.before  , ...
    params.frames.after  , ...
    'color_by','mouse', ...
    'mouse_ids',params.info.mouseid(1:24),'data_type', 'dff', 'save_directory','W:\Connie\results\Bassi2025\fig3\reviews\irrelevant_additive_test')
%%%dataset level
% 
% additivity_stats = test_irrelevant_sound_additivity( ...
%     context_data_updated, ...
%     24, ...
%     params.frames.before  , ...
%     params.frames.after  , ...
%     'color_by','dataset');

% %% irrelevant sounds
% additivity_stats = test_irrelevant_sound_additivity( ...
%     context_data, ...
%     22, ...
%     params.frames.before  , ...
%     params.frames.after  , ...
%     'color_by','dataset');
% 
% additivity_stats = test_irrelevant_sound_additivity( ...
%     context_data, ...
%     22, ...
%     params.frames.before  , ...
%     params.frames.after  , ...
%     'color_by','mouse', ...
%     'mouse_ids',params.info_4sweeps.mouseid)
% 
% %%
% context_data_updated.dff = context_data.dff(:,[1:4,6:22]);
% additivity_stats = test_irrelevant_sound_additivity( ...
%     context_data_updated, ...
%     21, ...
%     params.frames.before  , ...
%     params.frames.after  , ...
%     'color_by','dataset');