%% Neuron-dropping analysis for population-subsampled SVM outputs
% This script mirrors run_analysis_SVM_glm_inputs_final.m. Update the two
% site-specific paths below when running outside the original environment.

addpath(genpath('C:\Code\Github\behavior-analysis2\classifier'));
addpath(genpath('C:\Code\Github\behavior-analysis2'));

load('V:\Connie\results\opto_2024\context\data_info\info.mat');
info.task_event_type = 'choice';
[current_mice, onset_id, active_events] = default_data_info(info.task_event_type);
info.chosen_mice = current_mice;

%% Load accuracies and true population-size metadata
% Beta files are intentionally absent for these fits; beta_active is [].
[acc_active, shuff_acc_active, beta_active, ...
    acc_active_top, shuff_acc_active_top, svm_metadata] = ...
    wrapper_load_all_svm_data( ...
        info, ...
        'GLM_3nmf_pre', ...
        [info.task_event_type '_subsampled'], ...
        [], ...
        '_1');

assert(isempty(beta_active), ...
    'Population-subsampled SVM analyses should not depend on beta outputs.');

% acc_active_top/shuff_acc_active_top are empty because top_suffix is empty.
% In these population fits, cell type 4 inside acc_active is already the
% deterministic cumulative ranked-pyramidal analysis.

%% Reconstruct event indices exactly as in the existing plotting workflow
first_dataset_models = svm_metadata.all_model_outputs{1};
mdl_param = first_dataset_models{1, 1, 1};
event_onsets = find(histcounts( ...
    active_events, mdl_param.binns + active_events(1)));

% wrapper_plot_accuracy_boxplots passes event_onsets(onset_id) and
% plot_svm_across_datasets_barplots uses onset:(onset+4), inclusive.
event_window_indices = event_onsets(onset_id):(event_onsets(onset_id) + 4);

savepath = fullfile('W:\Connie\results\Bassi2025\fig2\SVM_1', ...
    [info.task_event_type '_neuron_dropping']);

%% Primary reviewer-facing figure: raw accuracy and observed-minus-shuffled
[neuron_dropping_summary, neuron_dropping_figure] = ...
    wrapper_plot_svm_neuron_dropping( ...
        acc_active, shuff_acc_active, ...
        svm_metadata.population_sizes, event_window_indices, ...
        savepath, [info.task_event_type '_neuron_dropping'], ...
        'CellTypeLabels', svm_metadata.celltype_labels, ...
        'DeterministicCellTypes', svm_metadata.deterministic_celltypes, ...
        'ReplicationUnit', 'datasets', ...
        'ShowIndividualDatasets', false);

%% Optional dataset overlays and normalized saturation-rate figure
wrapper_plot_svm_neuron_dropping( ...
    acc_active, shuff_acc_active, ...
    svm_metadata.population_sizes, event_window_indices, ...
    savepath, [info.task_event_type '_neuron_dropping_datasets'], ...
    'CellTypeLabels', svm_metadata.celltype_labels, ...
    'DeterministicCellTypes', svm_metadata.deterministic_celltypes, ...
    'ShowIndividualDatasets', true);

wrapper_plot_svm_neuron_dropping( ...
    acc_active, shuff_acc_active, ...
    svm_metadata.population_sizes, event_window_indices, ...
    savepath, [info.task_event_type '_neuron_dropping_normalized'], ...
    'CellTypeLabels', svm_metadata.celltype_labels, ...
    'DeterministicCellTypes', svm_metadata.deterministic_celltypes, ...
    'Representation', 'normalized_to_largest');

%% Selected-population time courses for a randomly sampled cell type
selected_population_sizes = [1, 3, 5, 7, 10, 20, 50];
celltype_id = 1; % Pyr
wrapper_plot_svm_acc_trace_by_population( ...
    acc_active, shuff_acc_active, svm_metadata.population_sizes, ...
    selected_population_sizes, celltype_id, mdl_param, event_onsets, ...
    savepath, [info.task_event_type '_population_traces'], ...
    'ShowShuffled', true, 'YLimits', [0.45, 0.9]);

%% Optional observed-minus-shuffled time-by-population heatmap
plot_svm_population_time_heatmap( ...
    acc_active, shuff_acc_active, svm_metadata.population_sizes, ...
    celltype_id, event_onsets, savepath, ...
    [info.task_event_type '_population_heatmap'], ...
    'Mode', 'observed-minus-shuffled');
